# Esta es la primera clase

In [1]:
from pylab import *
%matplotlib inline

# Interger, Float y Double

In [9]:
1/2

0

In [10]:
1./2

0.5

In [15]:
a=1.
b=2
c=a/b

print c

0.5


In [16]:
a*b

2.0

In [19]:
b**2

4

In [22]:
4**(0.5)

2.0

# Vectores

In [30]:
vector1= [1.,2.,3.,4.]
c= vector1[2]/2
print c
print "la primeara entrada es", vector1[0], "la segunda entrada es", vector1[1]

1.5
la primeara entrada es 1.0 la segunda entrada es 2.0


In [31]:
print vector1

[1.0, 2.0, 3.0, 4.0]


In [2]:
array([1.,2.,3.,4.])

array([ 1.,  2.,  3.,  4.])

In [37]:
a=["hola", [1,2,3], 507, 0.3]

In [39]:
a[1]

[1, 2, 3]

In [3]:
zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [4]:
vector2= ones(8)

In [5]:
print vector2

[ 1.  1.  1.  1.  1.  1.  1.  1.]
